### ISSUE TITLE
expose gradle gitExecAllRepos as task

### ISSUE THREAD

**Issue by xenoterracide** [brightsparklabs/gradle-multi-git#4]
would it be simple to expose `gitExecAllRepos` as a task so one could do things like `./gradlew git checkout -b MY-TICKET` without making tasks for commands you just want to pass through to git?

**Comment by al-jeyapal** [comment]
Unfortunately not. Gradle does not have an easy way of [passing in parameters](https://stackoverflow.com/questions/11696521/how-to-pass-arguments-from-command-line-to-gradle)

We'd end up needing to do something ugly with gradle/system properties, e.g.
`./gradlew execAllRepos '-Pmyargs=git,checkout,-b,MY-TICKET`

Which isn't really all that much better. If you find yourself needing to do a lot of nested git commands, it might be worth adding a function to you dotfiles to simplify it:
```
# bash

gitn() {
	[[ -z $1 ]] && echo 'No git command to execute' && return
	find -name ".git" -type d | sort | while read dir
	do
		echo "============================================================"
		echo "${dir%.git}"
		echo "============================================================"
		echo
		result=`cd "$dir/.." && git $@ 2>&1` 
		echo $result
		echo
	done
}

gitn checkout -b MY-TICKET
```
